# Generated by Django 4.1.2 on 2023-01-16 10:05

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_image_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=pyuploadcare.dj.models.ImageField(default=''),
        ),
    ]
