# Generated by Django 4.1.2 on 2023-04-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_phonecategory_phones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecategory',
            options={'verbose_name': 'Phonecategory', 'verbose_name_plural': 'Phonecategories'},
        ),
        migrations.AlterField(
            model_name='phones',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.phonecategory'),
        ),
    ]
