# Generated by Django 4.1.2 on 2023-04-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_phonecategory_options_alter_phones_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonecategory',
            name='image',
        ),
    ]
