# Generated by Django 4.1.2 on 2023-04-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_phonecategory_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonecategory',
            options={'verbose_name': 'phonecategory', 'verbose_name_plural': 'phonecategories'},
        ),
    ]
