# Generated by Django 4.1.2 on 2023-04-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_homeappliancescategory_homeappliances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
